### ISSUE TITLE
Empty question response

### ISSUE THREAD

**Issue by mathiasgodwin** [Seunope/aloc-endpoints#12]
They have been empty data response for some of the subject and it's never noted in the documentation.

take a look at this response:
=====================

      Response: #####################
      --------------------------------------------------

{subject: economics, year: 2005, type: utme}
{"subject":"economics","status":200,"data":[]}

**Comment by Seunope** [comment]
@mathiasgodwin I will review and revert soon

**Comment by Seunope** [comment]
<img width="1040" alt="Screenshot 2021-11-17 at 19 53 02" src="https://user-images.githubusercontent.com/6086663/142264348-cfc71503-880a-4512-8594-44f3deb777ce.png">

Probably the URL was not structured well. The URL below gave me the response above

`https://questions.aloc.ng/v2/q?subject=economics&year=2005&type=utme`

**Comment by mathiasgodwin** [comment]
> <img alt="Screenshot 2021-11-17 at 19 53 02" width="1040" src="https://user-images.githubusercontent.com/6086663/142264348-cfc71503-880a-4512-8594-44f3deb777ce.png">
> 
> Probably the URL was not structured well. The URL below gave me the response above
> 
> `https://questions.aloc.ng/v2/q?subject=economics&year=2005&type=utme`

Well, I can't really say but this is not the only subject with empty response and besides I tried this in 2 different programming languages and they all returned this empty result. I can share the code that produce such if you want.

Plus: 
some return questions not upto 40, if all this were noted in the documentation, we consumers would have prepared our code base to deal with such case. It has really been a great thing consuming your APIs but would be greater with those things fixed. Thanks

**Comment by Seunope** [comment]
Please share the code with me. I will also look at the "40 questions" bug

**Comment by mathiasgodwin** [comment]
> Please share the code with me. I will also look at the "40 questions" bug

Alright, should I send it to the email on  your git profile?

**Comment by Seunope** [comment]
> > Please share the code with me. I will also look at the "40 questions" bug
> 
> Alright, should I send it to the email on your git profile?

Yes you can.
