### ISSUE TITLE
Get all questions in set

### ISSUE THREAD

**Issue by mofeejegi** [Seunope/aloc-endpoints#2]
Could you kindly provide  documentation on how to obtain all questions in a certain query criteria? Like a query for all questions in chemistry 2013 utme.

**Comment by Seunope** [comment]
Currently, we limit the number of questions you can get per subject to 7.  We don't want to over load the API with all the 60 questions. Doing this, will put unnecessary data on the client application, but if more users request for this feature, we will definitely activate it. You can make API call like this

`https://questions.aloc.ng/api/q/7?subject=chemistry`
`https://questions.aloc.ng/api/q?subject=chemistry&year=2005`

We don't have chemistry 2013, try 2010. Please note, we did not have all the years for all the subjects. We are working on another open source application that give users the privileged to upload their questions.

Base on your request, we will publish all the years per subject this week in documentation.

**Comment by ESIDEM** [comment]
@Seunope This is a very awesome project, but I feel returning only 7 questions is not a nice idea.
Rather you can add on option for all the question in chemistry for example, it is left for the dev. to choose.
One thing that will make people use this API is flexibility.

**Comment by Seunope** [comment]
@ESIDEM Thanks for airing your opinion. We need two more people to make this request and we will create an endpoint that gives 50 questions in one api call

**Comment by Seunope** [comment]
@mofeejegi  we have added wiki to the project https://github.com/seunope/aloc-endpoints/wiki  This was made possible because you suggested it.

**Comment by imoris11** [comment]
I was running here to open a new issue. I was making a call to the API expecting just 10 questions for a DEMO, was receiving just 7. Thought I was doing something wrong :) .

Is it possible to update the max per request? > 25 would be great. Thanks 💯

**Comment by Seunope** [comment]
By next weekend we will enable this feature and publish the API endpoint. @imoris11 thanks for reaching out

**Comment by imoris11** [comment]
@Seunope Thank you! Life saver

**Comment by Seunope** [comment]
@mofeejegi  @imoris11 @ESIDEM  Thanks for all your suggestions. You can make one API call that will return 40 questions.

> https://questions.aloc.ng/api/m?subject=chemistry

Get questions on demand, but questions limit is 40

`https://questions.aloc.ng/api/q/23?subject=chemistry`
`https://questions.aloc.ng/api/q/30?subject=chemistry`
`https://questions.aloc.ng/api/q/4?subject=chemistry`

You can check Readme or [Wiki](https://github.com/Seunope/aloc-endpoints/wiki) for more details

**Comment by Seunope** [comment]
Issue have been resolved.
