### ISSUE TITLE
Endpoint failure exposing critical server info

### ISSUE THREAD

**Issue by walestormborn** [Seunope/aloc-endpoints#3]
<img width="638" alt="screen shot 2018-08-25 at 5 01 09 pm" src="https://user-images.githubusercontent.com/42701476/44621234-681d9800-a89a-11e8-8052-e8273aef7706.png">

**Comment by Seunope** [comment]
Whoops! How could I, have missed this....? Thank you very much @walestormborn . Issue resolved

**Comment by walestormborn** [comment]
Anytime @Seunope
