### ISSUE TITLE
Endpoint for getting a Mathematics UTME questions return post-utme question

### ISSUE THREAD

**Issue by tayoogunbiyi** [Seunope/aloc-endpoints#4]
Making a request to https://questions.aloc.ng/api/q?subject=mathematics&type=utme

Gives the response below

![image](https://user-images.githubusercontent.com/29612423/50960705-49751200-14c6-11e9-9203-ba2e6f990c4d.png)

It might not be an issue exactly but the developer might want exactly UTME question

**Comment by Seunope** [comment]
You are correct with your observation. This scenario happens when the API does not have the exam type or year of that subject in its database that was queried for.. Check our wiki  list of exam type, year supported for each subject https://github.com/Seunope/aloc-endpoints/wiki/Subject-&-Year
