### ISSUE TITLE
Random data is returned from the API when wrong input is sent.

### ISSUE THREAD

**Issue by didagu** [Seunope/aloc-endpoints#5]
The api returns random data when i don't input the year or i input a year that is out of bounds:
[https://questions.aloc.ng/api/q?subject=chemistry&year=&type=utme](url) or
[https://questions.aloc.ng/api/q?subject=chemistry&year=2222&type=utme](url)
Check the screenshot below for more information.

I will like to suggest that the error logging system should be improved to take in consideration wrong inputs.

![aloc](https://user-images.githubusercontent.com/11537985/51427005-60b4ad80-1bf2-11e9-8dd3-88e2bb17d9e2.png)

**Comment by Seunope** [comment]
@didagu Thank you so much for bringing this up. The API response to still return data if out of bounds year was supplied, was a deliberate behavior designed into the API. We are trying to prevent the need for users to know every **Year** or **ExamType** available before consuming the API. We currently don't cover all exam years so we want to reduce the need for checking the [wiki ](https://github.com/Seunope/aloc-endpoints/wiki/Subject-&-Year)to get list of supported years. However, the **message** in the API response gave this hint.

The most important parameter is the **subject**. I hope this helps

**Comment by didagu** [comment]
> @didagu Thank you so much for bringing this up. The API response to still return data if out of bounds year was supplied, was a deliberate behavior designed into the API. We are trying to prevent the need for users to know every **Year** or **ExamType** available before consuming the API. We currently don't cover all exam years so we want to reduce the need for checking the [wiki ](https://github.com/Seunope/aloc-endpoints/wiki/Subject-&-Year)to get list of supported years. However, the **message** in the API response gave this hint.
> 
> The most important parameter is the **subject**. I hope this helps

It is good that you are trying to be open but it will reduce the workload from the API consumer to have to check if the information he asked for is correct or not. Based on your response too, the consumer would not if you support questions from a particular year or not. Thanks for your reply and concern.

**Comment by Seunope** [comment]
You are  welcome. We are always glad to hear from our users. 

> 
> 
> > @didagu Thank you so much for bringing this up. The API response to still return data if out of bounds year was supplied, was a deliberate behavior designed into the API. We are trying to prevent the need for users to know every **Year** or **ExamType** available before consuming the API. We currently don't cover all exam years so we want to reduce the need for checking the [wiki ](https://github.com/Seunope/aloc-endpoints/wiki/Subject-&-Year)to get list of supported years. However, the **message** in the API response gave this hint.
> > The most important parameter is the **subject**. I hope this helps
> 
> It is good that you are trying to be open but it will reduce the workload from the API consumer to have to check if the information he asked for is correct or not. Based on your response too, the consumer would not if you support questions from a particular year or not. Thanks for your reply and concern.
